spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://140.143.181.108:10028/travel_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    url:  jdbc:mysql://127.0.0.1:3306/travel_db?characterEncoding=utf-8&useSSl=falsed
  jpa:
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

server:
  servlet:
    context-path: /travel
  port: 8080
